import fs from 'fs';

const FILE_PATH = './frontend/src/i18n/translations.js';
let content = fs.readFileSync(FILE_PATH, 'utf8');

// Convert to CJS
const cjsContent = content.replace('export default translations;', 'module.exports = translations;');
fs.writeFileSync('./scripts/temp_trans.cjs', cjsContent);

const { default: ts } = await import('./temp_trans.cjs');

// New keys to add
const newKeys = {
  en: {
    mobileNumber: "Mobile Number",
    welcomeBack: "Welcome back",
    signInToUacs: "Sign in to your UACS account",
    createAccount: "Create an account",
    createOne: "Create one",
    joinUacs: "Join UACS as an authorized administrator",
    fullName: "Full Name",
    department: "Department",
    optional: "(optional)",
    confirmPassword: "Confirm Password",
    register: "Register",
    demoLogin: "Demo Login",
    alertPreferences: "Alert Preferences",
    alertPreferencesSub: "Customize how you receive alerts",
    preferredLanguage: "Preferred Language",
    alertZone: "Alert Zone",
    smsNotifications: "SMS Notifications",
    receiveSms: "Receive critical alerts via SMS",
    savePreferences: "Save Preferences",
    emergencyContact: "Emergency Contact",
    emergencyContactSub: "Add a trusted contact to receive your critical alerts",
    contactMobile: "Contact Mobile Number",
    contactMobileHint: "They will automatically receive SMS broadcasts during critical emergencies.",
    addContact: "Add Contact",
    publicAlertsFeed: "Public Alerts Feed",
    publicAlertsSub: "Stay informed with the latest official communications.",
    noActiveAlertsTitle: "No Active Alerts",
    noActiveAlertsDesc: "All clear. There are no ongoing emergencies or broadcasts.",
    accountCreated: "Account Created!",
    redirecting: "Redirecting to dashboard...",
    dontHaveAccount: "Don't have an account?",
    profileSettings: "Profile Settings",
    profileSettingsSub: "Manage your personal information",
    sessionSignOut: "Session",
    signOutSub: "Sign out from this device"
  },
  hi: {
    mobileNumber: "मोबाइल नंबर",
    welcomeBack: "वापसी पर स्वागत है",
    signInToUacs: "अपने UACS खाते में साइन इन करें",
    createAccount: "खाता बनाएं",
    createOne: "नया बनाएं",
    joinUacs: "अधिकृत प्रशासक के रूप में UACS से जुड़ें",
    fullName: "पूरा नाम",
    department: "विभाग",
    optional: "(वैकल्पिक)",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    register: "रजिस्टर करें",
    demoLogin: "डेमो लॉगिन",
    alertPreferences: "अलर्ट प्राथमिकताएं",
    alertPreferencesSub: "अलर्ट प्राप्त करने के तरीके को अनुकूलित करें",
    preferredLanguage: "पसंदीदा भाषा",
    alertZone: "अलर्ट क्षेत्र",
    smsNotifications: "SMS सूचनाएं",
    receiveSms: "SMS के माध्यम से महत्वपूर्ण अलर्ट प्राप्त करें",
    savePreferences: "प्राथमिकताएं सहेजें",
    emergencyContact: "आपातकालीन संपर्क",
    emergencyContactSub: "महत्वपूर्ण अलर्ट प्राप्त करने के लिए एक विश्वसनीय संपर्क जोड़ें",
    contactMobile: "संपर्क मोबाइल नंबर",
    contactMobileHint: "उन्हें महत्वपूर्ण आपात स्थितियों के दौरान स्वचालित रूप से SMS प्रसारण प्राप्त होंगे।",
    addContact: "संपर्क जोड़ें",
    publicAlertsFeed: "सार्वजनिक अलर्ट फ़ीड",
    publicAlertsSub: "नवीनतम आधिकारिक संचार के साथ सूचित रहें।",
    noActiveAlertsTitle: "कोई सक्रिय अलर्ट नहीं",
    noActiveAlertsDesc: "सब ठीक है। कोई जारी आपात स्थिति या प्रसारण नहीं है।",
    accountCreated: "खाता बनाया गया!",
    redirecting: "डैशबोर्ड पर रीडायरेक्ट कर रहा है...",
    dontHaveAccount: "क्या आपके पास खाता नहीं है?",
    profileSettings: "प्रोफ़ाइल सेटिंग्स",
    profileSettingsSub: "अपनी व्यक्तिगत जानकारी प्रबंधित करें",
    sessionSignOut: "सत्र",
    signOutSub: "इस डिवाइस से साइन आउट करें"
  },
  mr: {
    mobileNumber: "मोबाईल नंबर",
    welcomeBack: "पुन्हा स्वागत आहे",
    signInToUacs: "तुमच्या UACS खात्यात साइन इन करा",
    createAccount: "खाते तयार करा",
    createOne: "नवीन तयार करा",
    joinUacs: "अधिकृत प्रशासक म्हणून UACS मध्ये सामील व्हा",
    fullName: "पूर्ण नाव",
    department: "विभाग",
    optional: "(पर्यायी)",
    confirmPassword: "पासवर्डची पुष्टी करा",
    register: "नोंदणी करा",
    demoLogin: "डेमो लॉगिन",
    alertPreferences: "अलर्ट प्राधान्ये",
    alertPreferencesSub: "तुम्हाला अलर्ट कसे मिळतात ते सानुकूलित करा",
    preferredLanguage: "आवडती भाषा",
    alertZone: "अलर्ट क्षेत्र",
    smsNotifications: "SMS सूचना",
    receiveSms: "SMS द्वारे महत्त्वपूर्ण अलर्ट प्राप्त करा",
    savePreferences: "प्राधान्ये जतन करा",
    emergencyContact: "आणीबाणी संपर्क",
    emergencyContactSub: "तुमचे महत्त्वपूर्ण अलर्ट प्राप्त करण्यासाठी विश्वसनीय संपर्क जोडा",
    contactMobile: "संपर्क मोबाईल नंबर",
    contactMobileHint: "त्यांना आणीबाणीच्या वेळी स्वयंचलितपणे SMS प्रसारण प्राप्त होईल.",
    addContact: "संपर्क जोडा",
    publicAlertsFeed: "सार्वजनिक अलर्ट फीड",
    publicAlertsSub: "नवीनतम अधिकृत संप्रेषणांसह माहितीपूर्ण राहा.",
    noActiveAlertsTitle: "कोणतेही सक्रिय अलर्ट नाहीत",
    noActiveAlertsDesc: "सर्व सुरळीत. कोणतीही आणीबाणी किंवा प्रसारण चालू नाही.",
    accountCreated: "खाते तयार केले!",
    redirecting: "डॅशबोर्डवर पुनर्निर्देशित करत आहे...",
    dontHaveAccount: "तुमचे खाते नाही का?",
    profileSettings: "प्रोफाइल सेटिंग्ज",
    profileSettingsSub: "तुमची वैयक्तिक माहिती व्यवस्थापित करा",
    sessionSignOut: "सत्र",
    signOutSub: "या डिव्हाइसवरून साइन आउट करा"
  },
  ta: {
    mobileNumber: "கைபேசி எண்",
    welcomeBack: "மீண்டும் வருக",
    signInToUacs: "உங்கள் UACS கணக்கில் உள்நுழைக",
    createAccount: "கணக்கை உருவாக்கு",
    createOne: "ஒன்றை உருவாக்கு",
    joinUacs: "அங்கீகரிக்கப்பட்ட நிர்வாகியாக UACS இல் சேரவும்",
    fullName: "முழு பெயர்",
    department: "துறை",
    optional: "(விருப்பத்திற்குரியது)",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    register: "பதிவு செய்",
    demoLogin: "டெமோ உள்நுழைவு",
    alertPreferences: "எச்சரிக்கை விருப்பங்கள்",
    alertPreferencesSub: "எச்சரிக்கைகளை எவ்வாறு பெறுவது என்பதை தனிப்பயனாக்குங்கள்",
    preferredLanguage: "விருப்பமான மொழி",
    alertZone: "எச்சரிக்கை மண்டலம்",
    smsNotifications: "SMS அறிவிப்புகள்",
    receiveSms: "SMS மூலம் முக்கியமான எச்சரிக்கைகளைப் பெறுக",
    savePreferences: "விருப்பங்களை சேமி",
    emergencyContact: "அவசர தொடர்பு",
    emergencyContactSub: "உங்கள் முக்கியமான எச்சரிக்கைகளைப் பெற நம்பகமான தொடர்பைச் சேர்க்கவும்",
    contactMobile: "தொடர்பு கைபேசி எண்",
    contactMobileHint: "அவசர காலங்களில் அவர்கள் தானாகவே SMS ஒளிபரப்புகளைப் பெறுவார்கள்.",
    addContact: "தொடர்பைச் சேர்",
    publicAlertsFeed: "பொது எச்சரிக்கைகள் ஊட்டம்",
    publicAlertsSub: "சமீபத்திய அதிகாரப்பூர்வ தகவல்களுடன் புதுப்பித்த நிலையில் இருங்கள்.",
    noActiveAlertsTitle: "செயலில் உள்ள எச்சரிக்கைகள் இல்லை",
    noActiveAlertsDesc: "எல்லாம் சீராக உள்ளது. அவசரகால அல்லது ஒளிபரப்புகள் எதுவும் இல்லை.",
    accountCreated: "கணக்கு உருவாக்கப்பட்டது!",
    redirecting: "கட்டுப்பாட்டு அறைக்கு திருப்பி விடுகிறது...",
    dontHaveAccount: "உங்களுக்கு கணக்கு இல்லையா?",
    profileSettings: "சுயவிவர அமைப்புகள்",
    profileSettingsSub: "உங்கள் தனிப்பட்ட தகவல்களை நிர்வகிக்கவும்",
    sessionSignOut: "அமர்வு",
    signOutSub: "இந்தச் சாதனத்திலிருந்து வெளியேறவும்"
  },
  te: {
    mobileNumber: "మొబైల్ నంబర్",
    welcomeBack: "తిరిగి స్వాగతం",
    signInToUacs: "మీ UACS ఖాతాలోకి సైన్ ఇన్ చేయండి",
    createAccount: "ఖాతాను సృష్టించండి",
    createOne: "ఒకటి సృష్టించండి",
    joinUacs: "అధీకృత నిర్వాహకుడిగా UACS లో చేరండి",
    fullName: "పూర్తి పేరు",
    department: "విభాగం",
    optional: "(ఐచ్ఛికం)",
    confirmPassword: "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    register: "నమోదు చేయండి",
    demoLogin: "డెమో లాగిన్",
    alertPreferences: "అలర్ట్ ప్రాధాన్యతలు",
    alertPreferencesSub: "మీరు అలర్ట్‌లను ఎలా స్వీకరిస్తారో అనుకూలీకరించండి",
    preferredLanguage: "ప్రాధాన్యత భాష",
    alertZone: "అలర్ట్ జోన్",
    smsNotifications: "SMS నోటిఫికేషన్‌లు",
    receiveSms: "SMS ద్వారా క్లిష్టమైన అలర్ట్‌లను స్వీకరించండి",
    savePreferences: "ప్రాధాన్యతలను సేవ్ చేయండి",
    emergencyContact: "అత్యవసర పరిచయం",
    emergencyContactSub: "మీ క్లిష్టమైన అలర్ట్‌లను స్వీకరించడానికి విశ్వసనీయ పరిచయాన్ని జోడించండి",
    contactMobile: "సంప్రదింపు మొబైల్ నంబర్",
    contactMobileHint: "అత్యవసర పరిస్థితుల్లో వారు స్వయంచాలకంగా SMS ప్రసారాలను అందుకుంటారు.",
    addContact: "పరిచయాన్ని జోడించండి",
    publicAlertsFeed: "ప్రజా అలర్ట్‌ల ఫీడ్",
    publicAlertsSub: "తాజా అధికారిక సమాచారంతో అప్‌డేట్‌గా ఉండండి.",
    noActiveAlertsTitle: "క్రియాశీల అలర్ట్‌లు లేవు",
    noActiveAlertsDesc: "అంతా ప్రశాంతంగా ఉంది. కొనసాగుతున్న అత్యవసర పరిస్థితులు లేదా ప్రసారాలు లేవు.",
    accountCreated: "ఖాతా సృష్టించబడింది!",
    redirecting: "డాష్‌బోర్డ్‌కు దారి మళ్లిస్తోంది...",
    dontHaveAccount: "మీకు ఖాతా లేదా?",
    profileSettings: "ప్రొఫైల్ సెట్టింగ్‌లు",
    profileSettingsSub: "మీ వ్యక్తిగత సమాచారాన్ని నిర్వహించండి",
    sessionSignOut: "సెషన్",
    signOutSub: "ఈ పరికరం నుండి సైన్ అవుట్ చేయండి"
  }
};

// Merge
for (const lang of Object.keys(newKeys)) {
  ts[lang] = { ...ts[lang], ...newKeys[lang] };
}

// Remove ur and bn
delete ts.ur;
delete ts.bn;

// Serialize back
const updatedContent = `const translations = ${JSON.stringify(ts, null, 2)};\n\nexport default translations;`;
fs.writeFileSync(FILE_PATH, updatedContent);

fs.unlinkSync('./scripts/temp_trans.cjs');
console.log('Translations updated successfully');
